import "bootstrap/dist/css/bootstrap.min.css";
import "jquery/dist/jquery.min.js";
import "popper.js/dist/popper.min";
import "bootstrap/dist/js/bootstrap.min.js";
import "./src/styles/global.css";
import "./src/styles/elegant-font-icons.css";
import "./src/styles/themify-icons.css";
import "./src/styles/et_line.css";
import "./src/styles/fontawesome.min.css";
